-- FishingConfigModule (ModuleScript in ReplicatedStorage.Modules)
return {
	FishingRod = {
		Distance = 60,
		Rarity = "Common",
		RodPower = 1.15,
		DifficultyMod = 1.0,
		HitZoneBonus = 1.2
	},
	["Silver Rod"] = {
		Distance = 80,
		Rarity = "Uncommon",
		RodPower = 1.2,
		DifficultyMod = 0.85,
		HitZoneBonus = 1.2
	},
	GoldRod = {
		Distance = 85,
		Rarity = "Rare",
		RodPower = 1.25,
		DifficultyMod = 0.825
	},
	CrystalRod = {
		Distance = 90,
		Rarity = "Epic",
		RodPower = 1.3,
		DifficultyMod = 0.8
	},
	MagneticRod = {
		Distance = 95,
		Rarity = "Epic",
		RodPower = 1.35,
		DifficultyMod = 0.75
	},
	BoneRod = {
		Distance = 100,
		Rarity = "Fantasy",
		RodPower = 1.4,
		DifficultyMod = 0.7
	},
	CloverRod = {
		Distance = 105,
		Rarity = "Mystic",
		RodPower = 1.45,
		DifficultyMod = 0.625
	},
	RainbowRod = {
		Distance = 110,
		Rarity = "Legendary",
		RodPower = 1.5,
		DifficultyMod = 0.55
	},
	UnknownRod = {
		Distance = 115,
		Rarity = "Unknown",
		RodPower = 1.55,
		DifficultyMod = 0.45
	},
	RobuxRod = {
		Distance = 115,
		Rarity = "Unknown",
		RodPower = 1.6,
		DifficultyMod = 0.45
	},
	ElectricRod = {
		Distance = 120,
		Rarity = "Unknown",
		RodPower = 1.65,
		DifficultyMod = 0.35
	},
	RealisticRod = {
		Distance = 120,
		Rarity = "Unknown",
		RodPower = 1.68,
		DifficultyMod = 0.2
	},
	BlockyRod = {
		Distance = 120,
		Rarity = "Unknown",
		RodPower = 1.68,
		DifficultyMod = 0.2
	},
	ArcaneRod = {
		Distance = 125,
		Rarity = "Unobtainable",
		RodPower = 1.75,
		DifficultyMod = 0.15
	},
	FlameRod = {
		Distance = 130,
		Rarity = "Unobtainable",
		RodPower = 1.82,
		DifficultyMod = 0.12
	},
	VoidRod = {
		Distance = 125,
		Rarity = "Unobtainable",
		RodPower = 2.0,
		DifficultyMod = 0.15
	},
	InviteRod = {
		Distance = 97,
		Rarity = "Epic",
		RodPower = 1.38,
		DifficultyMod = 0.73
	},
	FriendRod = {
		Distance = 120,
		Rarity = "Special",
		RodPower = 1.8,
		DifficultyMod = 0.1
	},
	DevRod = {
		Distance = 150,
		Rarity = "Unobtainable",
		RodPower = 1972,
		DifficultyMod = 0.1
	}
}
